#cloud-config

# https://cloudinit.readthedocs.io/en/latest/topics/modules.html#package-update-upgrade-install
package_update: true
package_upgrade: true
package_reboot_if_required: true

packages:
  - docker-ce

users:
  - name: ubuntu
    groups: docker

apt:
  preserve_sources_list: true
  sources:
    docker:
      keyid: 0EBFCD88
      keyserver: https://download.docker.com/linux/ubuntu/gpg
      source: deb https://download.docker.com/linux/ubuntu $RELEASE stable
snap:
    commands:
      - snap install powershell --classic

runcmd:
  - 'curl https://raw.githubusercontent.com/docker/cli/master/contrib/completion/bash/docker -o /etc/bash_completion.d/docker.sh && echo "complete -F _docker d # Added by DockerMultipass" >> /etc/bash_completion.d/docker.sh'

write_files:
  - content: |
      alias d='docker'
      alias sl='cd'
    path: /etc/profile.d/DockerMultipass-aliases.sh
  - content: |
      # Added by DockerMultipass
      set bell-style visible
    append: true
    path: /etc/inputrc
